// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRQyedAseuGjBgrrkUOp5JrgB4au7iZU',
    appId: '1:826668479598:web:d072d4eeaa139e1235e27f',
    messagingSenderId: '826668479598',
    projectId: 'ajs-stock',
    authDomain: 'ajs-stock.firebaseapp.com',
    storageBucket: 'ajs-stock.firebasestorage.app',
    measurementId: 'G-1EJKFSH0XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDigmsQkF06ePwgHanuojkR4n4tTYg9MU0',
    appId: '1:826668479598:android:c25c21ef3b302e1135e27f',
    messagingSenderId: '826668479598',
    projectId: 'ajs-stock',
    storageBucket: 'ajs-stock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ii5TDT8Wtd5mEPW9sK1q-MGtGpTF1tM',
    appId: '1:826668479598:ios:bd32060345a13ee635e27f',
    messagingSenderId: '826668479598',
    projectId: 'ajs-stock',
    storageBucket: 'ajs-stock.firebasestorage.app',
    iosBundleId: 'com.example.ajsStock2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ii5TDT8Wtd5mEPW9sK1q-MGtGpTF1tM',
    appId: '1:826668479598:ios:bd32060345a13ee635e27f',
    messagingSenderId: '826668479598',
    projectId: 'ajs-stock',
    storageBucket: 'ajs-stock.firebasestorage.app',
    iosBundleId: 'com.example.ajsStock2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARRQyedAseuGjBgrrkUOp5JrgB4au7iZU',
    appId: '1:826668479598:web:e648dadac30aabf235e27f',
    messagingSenderId: '826668479598',
    projectId: 'ajs-stock',
    authDomain: 'ajs-stock.firebaseapp.com',
    storageBucket: 'ajs-stock.firebasestorage.app',
    measurementId: 'G-G83ZXLP4N1',
  );

}